#!/usr/bin/env python3
"""Generate an embedded high-resolution proportional font atlas.

The native client cannot assume a font file or a font library exists on the
device. This tool rasterizes the local build font into a 48x48 grayscale atlas,
including both CJK and printable Latin glyphs. The renderer downsizes the atlas
with area averaging for each requested text size, so the device gets
proportional, antialiased text instead of a stretched 5x7 dot matrix.
"""

import os
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = [
    os.path.join(ROOT, "src", "renderer.cpp"),
    os.path.join(ROOT, "src", "model.cpp"),
]

FONT_CANDIDATES = [
    "/System/Library/Fonts/PingFang.ttc",
    "/System/Library/Fonts/Hiragino Sans GB.ttc",
    "/System/Library/Fonts/STHeiti Medium.ttc",
    "/System/Library/Fonts/STHeiti Light.ttc",
    "/System/Library/Fonts/Supplemental/Songti.ttc",
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
]

ATLAS_SIZE = 48
FONT_SIZE = 192
# The atlas cell is an em-sized slice of the source font. Keeping the source
# cell intact (instead of cropping every glyph to a square) preserves the
# font's real cap height, x-height, side bearings, and proportional advances.
# That is what makes Latin names read like a normal UI font at small sizes.


def collect_code_points():
    code_points = set()
    for path in SOURCES:
        with open(path, encoding="utf-8") as source:
            text = source.read()
        for character in text:
            code = ord(character)
            if code >= 0x20 and character not in "\r\n\t":
                code_points.add(ord(character))
    return sorted(code_points)


def find_font():
    for candidate in FONT_CANDIDATES:
        if os.path.exists(candidate):
            return candidate
    raise SystemExit("no local CJK font found; install one of the checked font paths")


def render_glyph(font, character):
    canvas = Image.new("L", (FONT_SIZE, FONT_SIZE), 0)
    draw = ImageDraw.Draw(canvas)
    draw.text((0, 0), character, fill=255, font=font)
    advance = max(1, round(font.getlength(character) / FONT_SIZE * ATLAS_SIZE))
    normalized = canvas.resize((ATLAS_SIZE, ATLAS_SIZE), Image.Resampling.LANCZOS)
    return advance, list(normalized.get_flattened_data())


def emit_header(path, glyphs):
    lines = [
        "#pragma once",
        "// Generated by native/tools/make_cjk_font.py; do not edit by hand.",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace aht {",
        "",
        "constexpr std::uint32_t kCjkGlyphWidth = %d;" % ATLAS_SIZE,
        "constexpr std::uint32_t kCjkGlyphHeight = %d;" % ATLAS_SIZE,
        "",
        "struct CjkGlyph {",
        "    std::uint32_t code;",
        "    std::uint16_t advance;",
        "    std::uint8_t pixels[kCjkGlyphWidth * kCjkGlyphHeight];",
        "};",
        "",
        "constexpr CjkGlyph kCjkGlyphs[] = {",
    ]
    for code, advance, pixels in glyphs:
        pixel_text = ", ".join(str(pixel) for pixel in pixels)
        lines.append("    {0x%04X, %d, {%s}}," % (code, advance, pixel_text))
    lines.extend(
        [
            "};",
            "",
            "constexpr std::size_t kCjkGlyphCount = sizeof(kCjkGlyphs) / sizeof(kCjkGlyphs[0]);",
            "",
            "inline const CjkGlyph* findCjkGlyph(std::uint32_t code) {",
            "    for (std::size_t index = 0; index < kCjkGlyphCount; ++index) {",
            "        if (kCjkGlyphs[index].code == code) {",
            "            return &kCjkGlyphs[index];",
            "        }",
            "    }",
            "    return nullptr;",
            "}",
            "",
            "} // namespace aht",
            "",
        ]
    )
    with open(path, "w", encoding="utf-8") as output:
        output.write("\n".join(lines))


def main():
    if len(sys.argv) != 2:
        print("usage: make_cjk_font.py <output.hpp>", file=sys.stderr)
        return 2
    font_path = find_font()
    font = ImageFont.truetype(font_path, FONT_SIZE)
    glyphs = [(code, *render_glyph(font, chr(code))) for code in collect_code_points()]
    emit_header(sys.argv[1], glyphs)
    print("generated %d proportional glyphs from %s" % (len(glyphs), font_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
